# Generated by Django 5.2.3 on 2025-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=150)),
                ('contactNumber', models.CharField(max_length=11)),
                ('location', models.TextField()),
                ('type', models.CharField()),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='Rescue_Photo/')),
                ('issueFaced', models.TextField()),
            ],
        ),
    ]
